// Pacote
package webTest;
// Generated by Selenium IDE
// Bibliotecas

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;
//2-Classes
public class LoginWD {
    // 2.1 -Atributos
    private WebDriver driver;  // Declaramos o bjeto Selenium webDriver
    //Fuões e Métodos
    private Map<String, Object> vars;
    JavascriptExecutor js;
    //private ChromeDriver driver;

    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        driver.manage().window().maximize();



        // Apontar onde está o chrome Driver
        System.setProperty("webdriver.chrome.driver","drivers/chrome/chromedriver.exe");
        driver = new ChromeDriver();           // Instancia / Liga o Chrome Driver
        driver = new ChromeDriver(options) ;   // Instancia / Liga o Chrome Driver
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void login() {
        driver.get("https://testando.eveclass.com/");
        driver.manage().window().setSize(new Dimension(1366, 768));
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("input[type=\"email\"]")).click();
        driver.findElement(By.cssSelector("input[type=\"email\"]")).sendKeys("lenesoares.souza@gmail.com");
        driver.findElement(By.cssSelector("input[type=\"password\"]")).sendKeys("081021");
        driver.findElement(By.cssSelector(".button-text>span")).click();
        driver.findElement(By.cssSelector(".context-title")).click();
        driver.findElement(By.cssSelector(".dropdown:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".dropdown_footer .infos-text")).click();
        driver.findElement(By.cssSelector(".swal2-confirm")).click();
    }
}
